// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class RedirectionUrl
    {
        public const string Codename = "redirection_url";
        public const string RedirectToCodename = "redirect_to";

        public string RedirectTo { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}